### PR TITLE
LUN-240: Escape slashes for browserstack upload

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

### CODE REVIEW

**Review by klinzo — COMMENTED** [review]
What is `////-` doing? Do you have a link where this behavior is described?

**Comment by SteffiStuffel** [comment]
> What is `////-` doing? Do you have a link where this behavior is described?

first `//` meas all occurrences are matched `//` is the escaped slash which should be replaced `-` is the char we want it wo replace with.
https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion

**Review by Taggotty — APPROVED** [review]
Nice 👍🏼  tested replacement locally in cmd

**Review by klinzo — APPROVED** [review]
Ah regex magic :+1:

**Pull request merged**
