### PR TITLE
LUN-418: Cut off words are fixed

### PR DESCRIPTION
**Pull request by lunars97**
This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

### CODE REVIEW

**Review by SteffiStuffel — APPROVED** [review]
Congratulations for your first PR :tada: 

Tested on normal and small Android emulator. Works just fine.

**Review by steffenkleinle — APPROVED** [review]
Well done, thanks for your first PR!

Not relevant for this PR: @SteffiStuffel should we perhaps rename `Feedback` to something like `SolutionFeedback`? I was really confused what this was about now that we have normal Feedback.

**Comment by SteffiStuffel** [comment]
> Well done, thanks for your first PR! blush
> 
> Not relevant for this PR: @SteffiStuffel should we perhaps rename `Feedback` to something like `SolutionFeedback`? I was really confused what this was about now that we have normal Feedback.

Fine for me. Please open a ticket.

**Comment by steffenkleinle** [comment]
> > Well done, thanks for your first PR! blush
> > Not relevant for this PR: @SteffiStuffel should we perhaps rename `Feedback` to something like `SolutionFeedback`? I was really confused what this was about now that we have normal Feedback.
> 
> Fine for me. Please open a ticket.

Done: https://issues.tuerantuer.org/browse/LUN-448

**Pull request merged**
