### PR TITLE
LUN-141: Remove exercise results and sessions from async storage

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

### CODE REVIEW

**Review by SteffiStuffel — APPROVED** [review]
Tested in Android. Works perfectly fine.

**Review by Taggotty — APPROVED** [review]
What will happen with the storage data that was already created?

And furthermore the color of the label of the `Eingabe Überprüfen` button seems off

**Comment by klinzo** [comment]
> What will happen with the storage data that was already created?

Good question, right now it will just be kept. I think that is fine as it shouldn't be a huge amount of data and does not hurt. Other opinions?
 
> And furthermore the color of the label of the `Eingabe Überprüfen` button seems off

Is this something new? There is already an issue for this (if I understood you correctly): https://issues.tuerantuer.org/browse/LUN-199

**Review by SteffiStuffel — APPROVED** [review]

**Comment by klinzo** [comment]
@Taggotty if you think this should be handled differently/be removed, please open an issue :)

**Pull request merged**
