### PR TITLE
LUN-367: Hide bottom tab bar for initial selection

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

### CODE REVIEW

**Comment by steffenkleinle** [comment]
Sadly it is not really possible to only hide the bottom tab bar if it is the initial selection, therefore I removed the bottom tab bar for every profession selection (which is fine imo). If this is a problem, the only solution would be to duplicate the route.

**Review by f1sh1918 — APPROVED** [review]
Tested on ios. 
SafeAreaView is missing so "Überspringen" Button is slightly overlapping bottom handler for ScopeSelection Screen
Gonna fix that in LUN-369 if we don't plan to release before

**Comment by steffenkleinle** [comment]
> Tested on ios. SafeAreaView is missing so "Überspringen" Button is slightly overlapping bottom handler for ScopeSelection Screen Gonna fix that in LUN-369 if we don't plan to release before
> 
> 

Was missing before, wasn't it? So won't fix here and lets do it in your issue :)

**Review by SteffiStuffel — APPROVED** [review]
Looks good. 
Tested on Android emulator.

**Pull request merged**
