### PR TITLE
LUN-154: Make screen scrollable

### PR DESCRIPTION
**Pull request by ansamshtaiwi1**
This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

### CODE REVIEW

**Comment by SteffiStuffel** [comment]
Tested on Android Emulator and ios Emulator. Works fine.

**Review by SteffiStuffel — APPROVED** [review]

**Comment by klinzo** [comment]
@ansamshtaiwi1 will you finish this issue? Otherwise we'll reassign it :) Thanks anyway!
@SteffiStuffel do you know anything here?

**Comment by ansamshtaiwi1** [comment]
> @ansamshtaiwi1 will you finish this issue? Otherwise we'll reassign it :) Thanks anyway! @SteffiStuffel do you know anything here?

**Comment by ansamshtaiwi1** [comment]
@klinzo   I tried several ways to solve the problem but unfortunately, I could not find the right way, so I prefer to reassign it. Thank you (:

**Comment by klinzo** [comment]
@ansamshtaiwi1 Sure! Thanks for your efforts and good luck :)

**Comment by maxammann** [comment]
@klinzo should rediscuss the way to go here in the grooming? I think something like this is required in ALL of our apps :)

The UX should be the same in all apps for such a usecase imo

**Pull request closed without merging**
