### PR TITLE
LUN-226: Adjust header of exercise screen

### PR DESCRIPTION
**Pull request by Taggotty**
This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

### CODE REVIEW

**Review by klinzo — COMMENTED** [review]
When selecting an exercise, the header is `Übersicht der Übungen`. I think it should be the name of the discipline there as well, e.g. `Grundlagen Werkzeuge` or `Dübel und Hobel`.

signal-2022-01-27-105748_001


Tested on Android :+1:

**Review by SteffiStuffel — APPROVED** [review]
Looks good. Also the "Übersicht der Übungen" header for an exercise is just fine and as it is in the designs.

**Comment by SteffiStuffel** [comment]
Tested on Android (browserstack)

**Comment by klinzo** [comment]
> Looks good. Also the "Übersicht der Übungen" header for an exercise is just fine and as it is in the designs.

Feels inconsistent to me but fine oc.

**Review by klinzo — APPROVED** [review]

**Pull request merged**
